install:
- bundle update --bundler
- bundle install
services:
- postgresql
script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:environment:set RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: X/cuyLvUMowf1H7xcMCmQ1kKWC0Lb3EHJ5PvDmRlxjxeq/EMPJftd/xJemoiE4BLIqJvs7FmrozY+MILxouo3L1a5zjqOEYu2mZ9/vX7bFaqTBAaKiORb4j6K317CqeS/A4OB+o17bG8DQAtfP4OlwyY3liH/aLO0uMKrJw1M5TxSP0BiopbAo9KA11OgYzYFdKPDmqKeO2e/urzElgLDe+oBPV/SUYZOc1mBYdbAjiAeXYlE5gZ+eP0TP36icpwPkZ6sCzVY+LRUSy0JnFvWVyPOL+NSNKvrPdaZK6U5oejjn+4w3ggnHB027dhWmtQJaJQ+fYPqBRtCNDxcBOnbm5kx+wF5VNS9JVks7tcChx8ZN78QTd7TvJe2ay/jOiVHUXfEwIimkIqbcNSw8U5kdNT3g7pyELiGMbv25Qt7ACTYSi2DYZkQtBT4LErpjkadBWsT34TOS76R5bck2ai/SwsFZ7yTqxnK3BHEt6fTCRJH9usTRtK7kE75vJMBIPAZ5L0Ofa3Zs5PSbWrdlaXJPuw7iwhUXH+VX1vGnF9GkPPzu47AbNVzXbri9dL2Z9GVWIui/T81OaWjRr3e0QglC/24TSRw1uMfRMcRt045mwQ8SIvCLdVY9kLtAkFIDPds7EvO7EEhEA1DBqsDmvGcbAK5CpnFEtTAAG/sLWe7U4=
  app: sclz
  on:
    repo: alexleesonmill/acebook-SCLZ
  skip_cleanup: 'true'
