install:
- bundle update --bundler
- bundle install
services:
- postgresql
script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rails db:environment:set RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: xrXq2efnpechoyzeZJSCzwQuzHRg+8flaz+rFd9D1RaH9YMVlCGvskZo3efhdFBw6JrnrGINkD8ZxAR8uaZnvrorgojltPrinnfZR8kiKjR7tiCUVu6Eh08itUuFAx6Eg78nXAzPzxzrpEq57GsNdj64IpZowG94iqG6WFWtUDHEfIc8m9nvSxyQTOMLqBkocb+6VwfoJEKEbnUnCqMmX/TV4X37idZQleEZgIKbtgG/p7Ue96EpC+OsTi64ET9p6V8QxLxgfQ/3P2s7yZ5Hkmba5pNI8jyEYE1VWnSm2MjnNO2qP7wF7ZSfQmaVpqtEGWuB/jxrE5MTyyV7LGgjRCHsPW6oSaTp5fo+fPww+YQMvrRd81TIRiZQc649iT08vvXd6UnYtMRgyyQLaKkT118Wau9GRxO9riaSyiPS2NIySQqOm9kFJAO4k+CQMQVwPMr/0UHHgzktuKFV+IJQ5knuxcjfQf5o9qIUXo8paAi5cMYIdf1hCUdZTwGHIa7GGcMl2sEtS3to/mQ9VG1mHAYxRGUdNROwEwtRNmZRrbiBZA4MxLOI8DdL0xSHHx5XBgk8EtUYqDplBlCNitnukgbh4f8Sv2JZAKJdT/78bXQWAK1N6trUTewOGiKfgqmDS+jJn3Ig2gXrCfFFNbYT+thDmU/bEp4ddtttXvPorUA=
    app: sclz
    on:
      repo: alexleesonmill/acebook-SCLZ
    run: 'rake db:migrate'
    skip_cleanup: 'true'
